name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:     
  deploy-staging:
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
      
    steps:
      # 1. Checkout (Clone) on the GitHub Actions runner
      - name: Checkout Code on Runner
        uses: actions/checkout@v4
        
      # 2. Setup rsync over SSH (Transfer)
      - name: Deploy Code via rsync over SSH (Safe Update)
        uses: burnett01/rsync-deployments@7.1.0
        with:
          path: .
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_path: ~/Workspace/juice-shop
          switches: -ah --exclude='.git/' --exclude='.github/' --no-o --no-g
          # -a flag ensures hidden files, e.g. .env.sample, .gitignore are pushed too.
          # --no-o --no-g attempts to maintain the ownership of the files on the server
          # One can remove the --exclude .git if tracking of changes on the server is desired.

      # 3. Restart the service on the remote server
      - name: Remote Setup and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/Workspace/juice-shop
            bash -ci 'npm i'
            bash -ci 'pm2 restart ecosystem.config.cjs'

  zap:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: ${{ secrets.APP_DOMAIN }}
      - name: Download Report Artifact
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
